AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Exclude:
    - "bin/*"
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/version.rb
    - db/schema.rb
    - "tmp/**/*"
    - "vendor/**/*"
    - Gemfile
    - Guardfile
    - Rakefile
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "config/**/*"
    - "app/uploaders/image_uploader.rb"

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Enabled: false
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "test/**/*"
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/LineLength:
  Exclude:
    - "config/**/*"
    - "db/**/*"

Metrics/MethodLength:
  Max: 12
  Exclude:
    - "db/migrate/*"
    - "test/**/*"

Naming/VariableNumber:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/**"

Rails/Validation:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
  Exclude:
    - "app/controllers/application_controller.rb"
    - "app/helpers/**/*_helper.rb"
    - "app/mailers/**/*_mailer.rb"
    - "app/models/application_record.rb"
    - "config/**/*"
    - "db/**/*"
    - "test/**/*"

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false
  EnforcedStyle: hash_rockets

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - before
    - let
    - let!
    - subject
    - watch
    - expect
